server:
  port: 9091
security:
  oauth2:
    resource:
      id: bcrypt
    client:
      access-token-validity-seconds: 1800
      authorized-grant-types: password,refresh_token
      client-id: teste
      client-secret: teste
      resource-ids: resources
      scope: read,write

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth-service
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true

